development: &development
  :url: redis://localhost:6379
  :host: localhost
  :port: 6379
  :timeout: 1
  :inline: true

test: *development

production: &production
  :url: redis://redistogo:7586c02013ac1c2d7e521bf7e0e1780e@chubb.redistogo.com:9793/
  :host: chubb.redistogo.com
  :port: 9793
  :password: 7586c02013ac1c2d7e521bf7e0e1780e
  :timeout: 1
  :inline: true
